import pandas as pd

# Leitura CSVs
producao = pd.read_csv("../src/csv/Producao.csv", sep=';')
processa_viniferas = pd.read_csv("../src/csv/ProcessaViniferas.csv", sep='\t')
processa_americanas = pd.read_csv("../src/csv/ProcessaAmericanas.csv", sep='\t')
processa_mesa = pd.read_csv("../src/csv/ProcessaMesa.csv", sep='\t')
processa_semclass = pd.read_csv("../src/csv/ProcessaSemclass.csv", sep='\t')
comercio = pd.read_csv("../src/csv/Comercio.csv", sep=';')
imp_vinhos = pd.read_csv("../src/csv/ImpVinhos.csv", sep=';')
imp_espumantes = pd.read_csv("../src/csv/ImpEspumantes.csv", sep=';')
imp_frescas = pd.read_csv("../src/csv/ImpFrescas.csv", sep=';')
imp_passas = pd.read_csv("../src/csv/ImpPassas.csv", sep=';')
imp_sucos = pd.read_csv("../src/csv/ImpSuco.csv", sep=';')
exp_vinhos = pd.read_csv("../src/csv/ExpVinho.csv", sep=';')
exp_espumantes = pd.read_csv("../src/csv/ExpEspumantes.csv", sep=';')
exp_uva = pd.read_csv("../src/csv/ExpUva.csv", sep=';')
exp_suco = pd.read_csv("../src/csv/ExpSuco.csv", sep=';')

# Conversao para JSON
comercio.to_json("../src/json/Comercio.json")
processa_viniferas.to_json("../src/json/ProcessaViniferas.json")
processa_americanas.to_json("../src/json/ProcessaAmericanas.json")
processa_mesa.to_json("../src/json/ProcessaMesa.json")
processa_semclass.to_json("../src/json/ProcessaSemclass.json")
producao.to_json("../src/json/Producao.json")
imp_vinhos.to_json("../src/json/ImpVinhos.json")
imp_espumantes.to_json("../src/json/ImpEspumantes.json")
imp_frescas.to_json("../src/json/ImpFrescas.json")
imp_passas.to_json("../src/json/ImpPassas.json")
imp_sucos.to_json("../src/json/ImpSuco.json")
exp_vinhos.to_json("../src/json/ExpVinho.json")
exp_espumantes.to_json("../src/json/ExpEspumantes.json")
exp_uva.to_json("../src/json/ExpUva.json")
exp_suco.to_json("../src/json/ExpSuco.json")
